### PR TITLE
Groupinstall skip 41

### LINKED ISSUE #41: Check if pak is already installed when running groupInstall(), rather than forcing / not forcing
Currently `groupInstall()` will attempt to upload and install all MPs. We can a utilize the `force` flags to either force install or skip, however, I think it would be more elegant to check if the solution already exists before attempting to do anything. This would allow groupInstall() to behave almost like configuration management.

### PR DESCRIPTION
**Pull request by rpocklington**
Resolves #41

### CODE REVIEW

**Comment by jsirianni** [comment]
@rpocklington are there any flags that need to be passed? I used `groupinstall` to upload a directory of MPs, and it works fine. I upload again, and it skips them but returns errors. I feel that it should state why it is skipping, and not return an error.

Or maybe I am testing this wrong, and this is desired behavior? 

output:
```
❯ ./vropscli.py groupInstall ~/Downloads/mp
Started Pak Upload: /Users/sirianjo/Downloads/mp/AmazonDynamoDB-6.3_1.1.0_b20180403.194313.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/AmazonDynamoDB-6.3_1.1.0_b20180403.194313.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["AmazonDynamoDB-6.3_1.1.0_b20180403.194313.pak","1.1.0.20180403.194313","1.1.0.20180403.194313"],"error_message":""}
Started Pak Upload: /Users/sirianjo/Downloads/mp/AmazonWebServices-6.3_1.0.0_b20180817.202920.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/AmazonWebServices-6.3_1.0.0_b20180817.202920.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["AmazonWebServices-6.3_1.0.0_b20180817.202920.pak","1.0.0.20180817.202920","1.0.0.20180817.202920"],"error_message":""}
Started Pak Upload: /Users/sirianjo/Downloads/mp/HPServers-6.3_2.1.4_b20181130.201532.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/HPServers-6.3_2.1.4_b20181130.201532.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["HPServers-6.3_2.1.4_b20181130.201532.pak","2.1.4.20181130.201532","2.1.4.20181130.201532"],"error_message":""}
Started Pak Upload: /Users/sirianjo/Downloads/mp/MicrosoftHyper-V-6.6_2.0.0_b20181207.182827.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/MicrosoftHyper-V-6.6_2.0.0_b20181207.182827.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["MicrosoftHyper-V-6.6_2.0.0_b20181207.182827.pak","2.0.0.20181207.182827","2.0.0.20181207.182827"],"error_message":""}
Started Pak Upload: /Users/sirianjo/Downloads/mp/OracleDatabase-6.3_1.2.2_b20180719.184130.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/OracleDatabase-6.3_1.2.2_b20180719.184130.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["OracleDatabase-6.3_1.2.2_b20180719.184130.pak","1.2.2.20180719.184130","1.2.2.20180719.184130"],"error_message":""}
Started Pak Upload: /Users/sirianjo/Downloads/mp/PostgreSQLAdapter-6.3_1.1.0_b20180402.155408.pak.  This may take up to 20 minutes depending on network speed.
Failed to upload pak /Users/sirianjo/Downloads/mp/PostgreSQLAdapter-6.3_1.1.0_b20180402.155408.pak
Skipping install
{"error_message_key":"upgrade.pak.upload_version_older_or_same","error_arguments":["PostgreSQLAdapter-6.3_1.1.0_b20180402.155408.pak","1.1.0.20180402.155408","1.1.0.20180402.155408"],"error_message":""}
Finished group install
```

**Comment by rpocklington** [comment]
@jsirianni 

I was about to write a long comment about thorough error handling would be a lot of extra effort... Then I finally realized that 99% of the time, the error will be "upgrade.pak.upload_version_older_or_same".

So I propose we add specific handling for that with a user-friendly message, and let other errors manifest as-is.

Thoughts?

**Comment by jsirianni** [comment]
> @jsirianni
> 
> I was about to write a long comment about thorough error handling would be a lot of extra effort... Then I finally realized that 99% of the time, the error will be "upgrade.pak.upload_version_older_or_same".
> 
> So I propose we add specific handling for that with a user-friendly message, and let other errors manifest as-is.
> 
> Thoughts?

Sorry for the large delay. I think that would be fine. Let me know if you want me to handle this. 👍

**Comment by jsirianni** [comment]
approving and merging, as this pr solves the issue. I created a new issue here to handle a future friendly error message https://github.com/BlueMedoraPublic/vropscli/issues/134

**Pull request merged**
